### ISSUE TITLE
Issue with Java HttpUrlConnection's Accept header

### ISSUE THREAD

**Issue by moulliet** [flightstats/hub#130]
From Lucas:

$ nc hub-v2.svc.staging 80
GET /channel/kratzen_ams/2015/03/19/03/47/55/655/ujs8Nb HTTP/1.1
User-Agent: Java/1.7.0_71
Host: hub-v2.svc.staging
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2

Stack trace from logs:
java.lang.IllegalArgumentException: java.text.ParseException: Expected separator '/' instead of ';'
	at com.sun.jersey.core.header.MediaTypes.createMediaTypes(MediaTypes.java:234) ~[jersey-bundle-1.19.jar:1.19]
	at com.flightstats.hub.channel.ChannelContentResource.contentTypeIsNotCompatible(ChannelContentResource.java:324) ~[hub-2015-03-18.7.jar:na]
	at com.flightstats.hub.channel.ChannelContentResource.getValue(ChannelContentResource.java:186) ~[hub-2015-03-18.7.jar:na]
--
Caused by: java.text.ParseException: Expected separator '/' instead of ';'
	at com.sun.jersey.core.header.reader.HttpHeaderReader.nextSeparator(HttpHeaderReader.java:121) ~[jersey-bundle-1.19.jar:1.19]
	at com.sun.jersey.core.impl.provider.header.MediaTypeProvider.valueOf(MediaTypeProvider.java:90) ~[jersey-bundle-1.19.jar:1.19]
	at com.sun.jersey.core.header.reader.HttpHeaderReader$2.create(HttpHeaderReader.java:320) ~[jersey-bundle-1.19.jar:1.19]
	at com.sun.jersey.core.header.reader.HttpHeaderReader$2.create(HttpHeaderReader.java:318) ~[jersey-bundle-1.19.jar:1.19]
	at com.sun.jersey.core.header.reader.HttpHeaderReader.readList(HttpHeaderReader.java:481) ~[jersey-bundle-1.19.jar:1.19]
	at com.sun.jersey.core.header.reader.HttpHeaderReader.readMediaTypes(HttpHeaderReader.java:325) ~[jersey-bundle-1.19.jar:1.19]
	at com.sun.jersey.core.header.MediaTypes.createMediaTypes(MediaTypes.java:228) ~[jersey-bundle-1.19.jar:1.19]

**Comment by moulliet** [comment]
The issue here is the media type "*; q=.2", which does not appear to be a valid media type, since it lacks a subtype - http://tools.ietf.org/html/rfc4288#section-4.2

If you remove that from the accept header, it should work.
