### ISSUE TITLE
Investigate Post error during rolling restart

### ISSUE THREAD

**Issue by moulliet** [flightstats/hub#181]
This only seems applicable to legacyScraperRaw

**Comment by moulliet** [comment]
WARN 2015-06-03 06:32:24,372 [qtp788684446-12130] com.flightstats.hub.spoke.SpokeContentDao [line 48] - what's up?
com.flightstats.hub.exception.ContentTooLargeException: max payload size is 20971520 bytes
	at com.flightstats.hub.spoke.SpokeMarshaller.toBytes(SpokeMarshaller.java:53) ~[hub-2015-05-20.53.jar:na]
	at com.flightstats.hub.spoke.SpokeMarshaller.toBytes(SpokeMarshaller.java:26) ~[hub-2015-05-20.53.jar:na]
	at com.flightstats.hub.spoke.SpokeContentDao.write(SpokeContentDao.java:36) ~[hub-2015-05-20.53.jar:na]
	at com.flightstats.hub.dao.aws.AwsContentService.insert(AwsContentService.java:65) [hub-2015-05-20.53.jar:na]
	at com.flightstats.hub.dao.ChannelServiceImpl.insert(ChannelServiceImpl.java:63) [hub-2015-05-20.53.jar:na]
	at com.flightstats.hub.channel.ChannelResource.insertValue(ChannelResource.java:116) [hub-2015-05-20.53.jar:na]
