### ISSUE TITLE
Handle multipart Post on single item endpoint

### ISSUE THREAD

**Issue by moulliet** [flightstats/hub#238]
Joel was trying multipart to the single endpoint, causing this:

java.lang.IllegalStateException: Request in context!
	at org.eclipse.jetty.server.Request.recycle(Request.java:1802) ~[jetty-server-9.3.1.v20150714.jar:9.3.1.v20150714]
	at org.eclipse.jetty.server.HttpChannel.recycle(HttpChannel.java:247) [jetty-server-9.3.1.v20150714.jar:9.3.1.v20150714]
	at org.eclipse.jetty.server.HttpChannelOverHttp.recycle(HttpChannelOverHttp.java:78) ~[jetty-server-9.3.1.v20150714.jar:9.3.1.v20150714]
	at org.eclipse.jetty.server.HttpConnection.onCompleted(HttpConnection.java:411) [jetty-server-9.3.1.v20150714.jar:9.3.1.v20150714]
	at org.eclipse.jetty.server.HttpChannel.onCompleted(HttpChannel.java:558) [jetty-server-9.3.1.v20150714.jar:9.3.1.v20150714]
	at org.eclipse.jetty.server.HttpChannel.onBadMessage(HttpChannel.java:595) [jetty-server-9.3.1.v20150714.jar:9.3.1.v20150714]
	at org.eclipse.jetty.server.HttpChannelOverHttp.badMessage(HttpChannelOverHttp.java:256) ~[jetty-server-9.3.1.v20150714.jar:9.3.1.v20150714]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1306) ~[jetty-http-9.3.1.v20150714.jar:9.3.1.v20150714]
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:343) [jetty-server-9.3.1.v20150714.jar:9.3.1.v20150714]
	at org.eclipse.jetty.server.HttpConnection.fillAndParseForContent(HttpConnection.java:278) [jetty-server-9.3.1.v20150714.jar:9.3.1.v20150714]
	at org.eclipse.jetty.server.HttpInputOverHTTP.produceContent(HttpInputOverHTTP.java:33) ~[jetty-server-9.3.1.v20150714.jar:9.3.1.v20150714]
	at org.eclipse.jetty.server.HttpInput.nextContent(HttpInput.java:177) ~[jetty-server-9.3.1.v20150714.jar:9.3.1.v20150714]
	at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:136) ~[jetty-server-9.3.1.v20150714.jar:9.3.1.v20150714]
	at java.io.InputStream.read(InputStream.java:101) ~[na:1.8.0_45]
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:99) ~[guava-19.0-rc1.jar:na]
	at com.flightstats.hub.spoke.SpokeMarshaller.toBytes(SpokeMarshaller.java:48) ~[hub-08-19.1.batch-write.jar:na]

**Comment by joelhoffman** [comment]
this use should result in a single document with the original multipart encoding.
