### ISSUE TITLE
Occasional 404's for existing data

### ISSUE THREAD

**Issue by benFlightStats** [flightstats/hub#715]
Occasional 404's.  Can later bring up data manually. Crozier's app does not yet have retry - so we don't yet know if/how long the 404's persist.

[2:56 PM] Crozier, M.: I think that we are seeing intermittent 404's from the Hub for pretty old data.
[2:57 PM] Crozier, M.: For instance this. At Feb 9th 22:16, we got a 404 fetching an item from Feb 8thERROR [2017-02-09 22:16:43,336] com.flightstats.flightpositions.historical.index.work.URIProcessingTask: handling exception and sleeping
historicalflightpositionsindex_1  | ! com.flightstats.hub.HubException: http status=404, source: http://hub.iad.prod.flightstats.io/channel/positionsTfmsFlightPlan/2017/02/08/13/31/06/453/CXOxTS?ta...:

Crozier, M.·3:08 PM

Oh, Here is the corresponding haproxy log line with the 404:

Feb  9 22:16:43 proxy-hub-02.iad.prod.flightstats.io haproxy[1368]: 10.11.15.242:40806 [09/Feb/2017:22:16:40.814] hub-v2-http-in hub-iad-prod/hub-prod-iad-02 0/0/1/2521/2522 404 117 - - ---- 104/104/1/2/0 0/0 "GET /channel/positionsTfmsFlightPlan/2017/02/08/13/31/06/453/CXOxTS?tag=flightPlanPositions HTTP/1.1"

**Comment by benFlightStats** [comment]
Crozier, M.·3:12 PM
Sean just corrected me. We do retry after 2 seconds and it always appears to succeed.

**Comment by moulliet** [comment]
This was caused by a DNS error

Caused by: java.net.UnknownHostException: hub<snip>.s3-external-1.amazonaws.com
	at java.net.InetAddress.getAllByName0(InetAddress.java:1280)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27)
	at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76)
	at com.amazonaws.http.conn.$Proxy47.connect(Unknown Source)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
